### ISSUE TITLE
Parsing of single cell values ('bat [index]')

### ISSUE THREAD

**Issue by Naiki92** [chinezbrun/pytes_esp#2]
Are there any plans of including parsing for all cells of a single battery?

```
PYTES>bat 3
@
Battery  Volt     Curr     Tempr    Base State   Volt. State  Curr. State  Temp. State  Coulomb     
0        3548     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
1        3548     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
2        3548     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
3        3548     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
4        3548     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
5        3548     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
6        3520     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
7        3548     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
8        3545     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
9        3546     0        21000    Idle         Normal       Normal       Normal       100%      98900 mAH
10       3548     0        20000    Idle         Normal       Normal       Normal       100%      98900 mAH
11       3547     0        20000    Idle         Normal       Normal       Normal       100%      98900 mAH
12       3546     0        20000    Idle         Normal       Normal       Normal       100%      98900 mAH
13       3547     0        20000    Idle         Normal       Normal       Normal       100%      98900 mAH
14       3531     0        20000    Idle         Normal       Normal       Normal       100%      98900 mAH
15       3548     0        20000    Idle         Normal       Normal       Normal       100%      98900 mAH
Command completed successfully
$$
```

**Comment by chinezbrun** [comment]
Parsing all cells was not in scope. The main goal was stability and to have as much as possible a clean script and simple communication with the BMS. However, the issue was marked as enhancement without having a milestone. Depending on user votes / ratings for the issue, I may re-evaluate.

**Comment by axwell** [comment]
i would also like this 👍 

PS: Thank you for the library

**Comment by chinezbrun** [comment]
INFO: according latest Pytes firmware versions, current was removed from reporting after 'BAT' command, so, the single cells monitoring  becomes more difficult to be implemented. Anyhow, I leave the issue still open.

**Comment by chinezbrun** [comment]
news: 
cells monitoring will be implemented first in [pytes_serial. ](https://github.com/chinezbrun/pytes_serial)
0.7.0 is now in beta testing. test results are promising, despite the increasing time with 50% for overall reading/parsing.
after a while, with no bugs, i will try the functionality also on ESP32 version.

**Comment by chinezbrun** [comment]
@axwell, @Naiki92 please test and confirm. Please note that devices previous created should be deleted in Home Assistant as the MQTT discovery  routine was changed. If no change will be done in config.py 'dev_name' the sensors will be restored as previous and history maintained. Take also note that by default cells_monitoring is disabled, set it "true"  :)

**Comment by axwell** [comment]
@chinezbrun  thanks ! uploaded the new version, stable until now ~2h, i will get back to you if i spot any issues.
