### ISSUE TITLE
loop stops with cells monitoring activated (9 batteries)

### ISSUE THREAD

**Issue by fostersimp** [chinezbrun/pytes_esp#7]
Hi chinezbrun, 

I have been using this for a while an had no issues with cells = false.

When ever I have cells = True, the first data is collected and I can see it in Home-assistant, however I think it crashes as it stops sending any more data. 

I have 9 Plyontech US3000C, so its creating a lot of data

**Comment by chinezbrun** [comment]
Indeed there is a lot of data. 
Program tested with 6 batteries. so 9... is a new milestone :).
If not used already, you could try auto restart function to keep it alive.
Second option is to increase the 'reading_freq' in config.py

**Comment by fostersimp** [comment]
as the auto_reboot is in days would it work if I set it to 0.007 ~ 10 mins. 
reading_freq' in config.py is set to 60 seconds, perhaps it needs to be longer
I will try it tomorrow. 
Thanks for the fast response

**Comment by chinezbrun** [comment]
reading_freq is ok 60s no need to increase. Try with auto reboot less than one day. How long is the  round_trip value for 9 batteries ?

**Comment by fostersimp** [comment]
I attempted a reboot within a day, but that didn't resolve the issue.

I've observed that after the initial boot sequence and the start of the main loop, the first loop operates as intended. However, the second loop fails to complete; it writes data to the buffer and reaches the "check cells: ok" stage, where it stops or crashes.

A manual reset leads to the same outcome.

Please find the attached file for reference.

[9_US3000C_Loop_Stops.txt](https://github.com/user-attachments/files/17563201/9_US3000C_Loop_Stops.txt)

**Comment by chinezbrun** [comment]
can't figure if something wrong. sequence is ok, parsing round trip is ok. seems that is stuck in MQTT loop somehow. are you sure that  your connection is ok in that area? do you have more logs available or only for two loops? script stopped with any error message?

**Comment by fostersimp** [comment]
yes, no issues with the connection, when cells = False, it has been working for months without any issue. only when cells = true does it get stuck and its always at the same point, the second loop.

I can get more logs when cells = false if you like, and I can leave it running for cells = true and a auto reboot to 1 day.  However I think it will just get stuck at the same point, is there a way I can do some debug level logging ?

**Comment by chinezbrun** [comment]
leave it running with cells = true and  auto reboot set to 1 day to get more log.  there is no debug level logging available. 
no error message? simply stuck and no response? 

second loop is the same as first loop so... should be something else :)
i hope that you configure corect number of cells for pylontech.
please check also the sensors in HA, any particular observation (i.e one cell parameter that remains not updated)?

**Comment by chinezbrun** [comment]
any new elements?

**Comment by fostersimp** [comment]
Hi,

So I tested with Cells = true and 9 pylon-tech modules. The  initialization and first mqtt publish is successful, then second loop always stops at check cells :ok it never reaches mqtt publish. This is completely repeatable.

I reduced the modules to 6 and the results we sporadic with it failing to mqtt publish, and different loop intervals between 6 & 15.

I further reduced the modules to 3 and stopped testing after around 150 loops
[3-batterys_Cells-True.txt](https://github.com/user-attachments/files/17602823/3-batterys_Cells-True.txt)

I was wandering if it is something to do with the amount of data, I am only really interested in the cell voltage and status, perhaps you can guide me on how to modify the code to only collect that data. 

I also want to load an mqtt client onto the computer as well to rule out if Home Assistance could be the issue.

Thanks in advance
Don

**Comment by chinezbrun** [comment]
well Don, you have to think that for 9 batteries there are around 1000 sensors that needs to be updated.
That's why activation of the cells monitoring on the ESP version was debatable see https://github.com/chinezbrun/pytes_esp/issues/2. So, i will not recomand to activate this option with more than 4 batteries for stable results.

I don't think that Home Assistant is the issue, the program seems to stuck in MQTT transmision. 

Anyhow you can try the debug [main.txt](https://github.com/user-attachments/files/17603481/main.txt). Change the txt extension with py and upload it to ESP. Please send me the output and both files that will be created in the ESP root directors. If first loop pass we can have both of them.

**Comment by chinezbrun** [comment]
After that let isolate the issue: go to line 928 and remark it. 
![image](https://github.com/user-attachments/assets/03ba6803-3d88-46b4-ac62-fcc70244ab13)

restart the ESP and let see if the programs stops.

**Comment by fostersimp** [comment]
Hi,
So I loaded the debug main.py, I have attached the files requested. As for line 928, I will test that in a moment.

Don

[pylon_esp_status.json](https://github.com/user-attachments/files/17608467/pylon_esp_status.json)
[pylon_esp_status_old.json](https://github.com/user-attachments/files/17608468/pylon_esp_status_old.json)
[Main_Debug_Logs.txt](https://github.com/user-attachments/files/17608469/Main_Debug_Logs.txt)

**Comment by fostersimp** [comment]
Hi,

Today I tested with the debug main.py with mqtt publish enabled, the loop successfully completed on the first run, the second loop it did not complete the publish, see attached mqtt-publish logs/files

With line 928 remarked, i left the esp runing for round 30 loops, again please see the corresponding logs/files

Cheers Don

[mqtt-publish.zip](https://github.com/user-attachments/files/17609799/mqtt-publish.zip)
[mqtt_no-publish.zip](https://github.com/user-attachments/files/17609800/mqtt_no-publish.zip)

**Comment by chinezbrun** [comment]
Thanks! It is clear that ESP32 do not have enough memory to handle such amount of data. 

You have few options to try:
1. ESP32 with more memory
2. Switch to Raspberry Pi and run the pytes_serial

Meanwhile i opened https://github.com/chinezbrun/pytes_serial/issues/38 hoping that will work also on your case.

**Comment by chinezbrun** [comment]
please try  [main.zip](https://github.com/user-attachments/files/17610982/main.zip)
you should add to config.py one more line in cells monitoring section
monitoring_level       = "low"
see below:
![image](https://github.com/user-attachments/assets/f8f4e8ac-36fa-4142-81ff-ac8cbe852100)
delete in home assistant created devices and restart the ESP32.
let me know the results

**Comment by fostersimp** [comment]
Hi,

I have tested as you described, and seem's to be working reliably, i let it run for 27 loops, and it seems to be processing the data faster. I will now leave it run overnight, logs are attached.

I think you can also reduce the sensor count on the temperature sensors, as I believe that Pylontech have 3 banks of 5 cells each and only one temperature sensor per bank.

[Pylontech Battery Temps.xlsx](https://github.com/user-attachments/files/17612092/Pylontech.Battery.Temps.xlsx)


[Latest_Data.zip](https://github.com/user-attachments/files/17612004/Latest_Data.zip)

**Comment by chinezbrun** [comment]
Ok. Thanks for conducting the tests.
Program is designed for both type of batteries(Pylon and Pytes). Pytes has temperature sensors on every single cell so,  voltage and temperature are the minimum number of sensors that should be active in cells_monitoring. 
Please check and confirm if all ok in this configuration.

**Comment by fostersimp** [comment]
I left it running and it seemed to have stopped, to be honest I was not 100% sure, I was looking at the data in Home Assistant.

I set debug to false, and it has been runing for 14 hrs or so:

[896-loops.txt](https://github.com/user-attachments/files/17623552/896-loops.txt)


<img width="271" alt="image" src="https://github.com/user-attachments/assets/f3b35450-bbcb-4719-b1f0-e65d78d87473">

Thanks for your help :-), my only other thought for this when monitoring cells, would be to disable the long term statistics in home assistant.  My reason to enable cells is because I occasionally get a high voltage warning on my inverter

**Comment by chinezbrun** [comment]
please set the reading frequency back to 10s and let the program to run. We need to see if it is stable in this configuration at least 24h....anyhow is close to ESP32 capability :)

**Comment by fostersimp** [comment]
OK, just set the frequency to 10's I will update in the next day or so

**Comment by fostersimp** [comment]
So, keeping the read frequency to 10's it stops running.
With debug=true ~16 loops, on the 16th loop alocated mem: 88496 and free mem    : 56272.

With debug=false ~650 loops

[Debug_False_10s.txt](https://github.com/user-attachments/files/17653533/Debug_False_10s.txt)
[Debug_True_10s.txt](https://github.com/user-attachments/files/17653534/Debug_True_10s.txt)

**Comment by chinezbrun** [comment]
it is a memory issue and in this case is normal to work better when debug is false. 
send me pls both files created by debug, too. 
increase the reading frequency for 30 sec, deleted both json files created by debug. use the main from attach with debug = false
[main.zip](https://github.com/user-attachments/files/17656471/main.zip)

**Comment by chinezbrun** [comment]
The new version [0.5.0](https://github.com/chinezbrun/pytes_esp/releases/tag/v0.5.0) includes the option for monitoring level. 

In your case, please select "low", which will use less memory and give you the minimum number of sensors (only "voltage" without statistics). 

If this doesn't solve your problem, I strongly recommend you to disable "cells_monitoring" or switch to the fully fladged program [pytes_serial](https://github.com/chinezbrun/pytes_serial) which can run on a more powerful devices and can handle large amount of data better.

**Comment by chinezbrun** [comment]
I would like to thank you to trigger this update [0.5.0] that was planned but didn't come as a priority. I closed this issue as we are playing at the border of ESP32 memory, so nothing else can be done except what was already mentioned.

**Comment by fostersimp** [comment]
Thank you for your fast support, I have been busy over the last few days, never the less here are the tests you asked for. 

I will install version 0.5.0 and let you know in how I get on, at least I now know what was causing the issue. 

Thanks again

Don

> it is a memory issue and in this case is normal to work better when debug is false. send me pls both files created by debug, too. increase the reading frequency for 30 sec, deleted both json files created by debug. use the main from attach with debug = false [main.zip](https://github.com/user-attachments/files/17656471/main.zip)

[Tests.zip](https://github.com/user-attachments/files/17703222/Tests.zip)

**Comment by fostersimp** [comment]
Hi, version 0.5.0 has been working in 'low' with out any issues. Thank you for your support 👍
