### ISSUE TITLE
V0.5.0 'variable not defined' error

### ISSUE THREAD

**Issue by Banana5kin** [chinezbrun/pytes_esp#8]
Hi there, I am getting the below error when running the v0.5.0 python code.  Version 0.4.0 works perfectly

START - PytesSerial_Esp v0.5.0_20241107
...wlan started in the disconnected state, trying to connect
...wlan connection successful
..... ('XXX.XXX.X.XX', '255.255.255.0', 'XXX.XXX.X.XXX', 'XXX.XXX.X.XXX')
..... (2024, 12, 17, 18, 46, 40, 1, 352)
...serial initialization complete
...mqtt initialization complete
...mqtt auto discovery - system sensors:100 %
...mqtt auto discovery - battery sensors:100 %
...mqtt auto discovery - cell sensors:100 %
...mqtt auto discovery - statistics sensors:100 %
...program initialisation completed starting main loop
relay local time: 2024-12-17 18:46
serial uptime   : 0.0
...timeouts -> close serial, skip set
...serial stat   : loops: 1 errors: 1 efficiency: 0.0
...serial stat   : parsing round-trip: 8.06
Traceback (most recent call last):
  File "main.py", line 961, in <module>
NameError: name 'statistics_time' isn't defined
MicroPython v1.24.1 on 2024-11-29; Generic ESP32 module with OTA with ESP32
Type "help()" for more information.

**Comment by chinezbrun** [comment]
pls check. issue was fixed in 0.5.1

**Comment by Banana5kin** [comment]
> pls check. issue was fixed in 0.5.1

The latest version I can see is 0.5.0, am I missing something?

**Comment by chinezbrun** [comment]
the release is not published yet. you can find the main.py 0.5.1 in the repository

**Comment by chinezbrun** [comment]
@Banana5kin please confirm the fix.

**Comment by Banana5kin** [comment]
Hi Dan,

Yes, this has fixed the issue.  Many thanks.
